### PR TITLE
Add ADR for genome identifiers

### PR DESCRIPTION
**Pull request by nicklangridge**
This PR will merge the ADR for genome id as per the draft google document that has previously been circulated. Please review and raise any issues in the comments.

### CODE REVIEW

**Comment by azangru** [comment]
The identifier that is currently being used for 2020 consists of a combination of genome production name and assembly accession id (see field `genome_id` in response from https://2020.ensembl.org/api/genome/info?genome_id=triticum_aestivum_GCA_900519105_1).

This identifier is generated using a different principle than `assembly_id` (see [example in the core data modelling repo](https://github.com/Ensembl/core-data-modelling/blob/master/assembly.json)), but has the same semantics, being capable to precisely identify a particular assembly of a genome.

I do not know whether this means we need to switch to using the name `assembly_id`. Using it without updating the code accordingly may lead to confusion; and in the frontend code it has already become quite a central name (~210 places where it's currently used, according to `git grep`).

**Comment by andrewyatz** [comment]
Thanks for the links. Reading through the core data modelling descriptions it says `assembly_id` is `A unique identifier for the assembly. This represents an internal identifier.`. I think both conceptually and semantically the `genome_id` generated here is one and the same. Just the source data/examples used in CDM is an auto-increment numeric represented as a string and the one here is based on attributes of the assembly/genome.

@nicklangridge I think this really means to get the ADR approved I want to make sure we are in-alignment with CDM. 

It's worrying that we've already used the name ~210 times *but* it's better to change it now than further down the line when that grows to say ~2100 times

**Comment by nicklangridge** [comment]
> I think both conceptually and semantically the genome_id generated here is one and the same

Possibly, but there are some areas that need clarifying. 

In this ADR we are proposing that genome_id represents a 1-to-1 link between species and assembly.

In the latest core data model (see screenshot), the relationship between assembly and speices is via membership and is show as many-to-many.  
assembly_membership_species

I think we need more clarity from the core data model about how the species membership works.
In particular, how are hybrid species such as the existing assemblies for "Hybrid - Bos Indicus" and "Hybrid - Bos Torus" represented?

**Comment by andrewyatz** [comment]
Agreed and will raise at tomorrow's CDM meeting for you

**Comment by andrewyatz** [comment]
Changes made. Please review

**Pull request merged**
